parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: hit_switch
    database_user: %hitswitch.database.user%
    database_password: %hitswitch.database.password%
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: %hitswitch.secret%
    auth0_url: https://tl8.au.auth0.com
    auth0_client_id: %hitswitch.auth0_client_id%
    auth0_client_secret: %hitswitch.auth0_client_secret%
    token_length: 180
    token_expiry: 8
    rate_limit: 60
    reset_token_code: refresh
    admins:
        facebook:
            - "myfacebook.id"