
security:
    providers:
        hwi:
            id: hwi_oauth.user.provider.entity

    role_hierarchy:
        ROLE_CMS_ADMIN: ROLE_OAUTH_USER
        ROLE_ADMIN:     ROLE_CMS_ADMIN

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_OAUTH_USER }
        - { path: ^/admin/settings, roles: ROLE_ADMIN }
        - { path: ^/edit, roles: ROLE_CMS_ADMIN }
        - { path: ^/[0-9A-Za-z]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }

