<?php

namespace Frontend\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CmspageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmspageRepository extends EntityRepository
{
}
