<?php

namespace Backend\APIBundle\Repository;

/**
 * MessageLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
