services:
    backendapi.event.process_actions:
        class: Backend\APIBundle\EventListener\ProcessActionsListener
        arguments:
            - "@doctrine"
        tags:
            - {name: kernel.event_listener, event:backendapi.event.process_actions, method:handler} 

